---
fail_fast: false

default_stages:
  - pre-commit

repos:
  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: v4.0.2
    hooks:
      - id: editorconfig-checker
        name: editorconfig
  - repo: https://github.com/codespell-project/codespell
    rev: 'v2.4.3'
    hooks:
      - id: codespell
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        files: \.(yaml|yml)$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
